# Generated by Django 5.0.2 on 2024-02-15 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggapp', '0002_component_address_cartitems_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='images')),
                ('breed', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='Description about pet', max_length=255)),
            ],
            options={
                'db_table': 'pet',
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='components',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ggapp.pet'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ggapp.pet'),
        ),
        migrations.DeleteModel(
            name='Component',
        ),
    ]
