# Generated by Django 5.0.2 on 2024-02-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggapp', '0003_pet_remove_orderitem_components_orderitem_pet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='images')),
                ('age', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='Description about Component', max_length=255)),
            ],
            options={
                'db_table': 'Pc',
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='pet',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ggapp.pc'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ggapp.pc'),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
