# Generated by Django 5.0.2 on 2024-02-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggapp', '0004_pc_remove_orderitem_pet_remove_cartitems_pet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='name',
            new_name='component',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='age',
        ),
    ]
