# Generated by Django 5.0.2 on 2024-02-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggapp', '0005_rename_name_cartitems_component_remove_pc_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='name',
            new_name='component',
        ),
    ]
